version: '3.8'

services:

  db:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=maxbot
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=maxbot_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

  bot:
    build: .
    env_file: .env
    restart: always
    depends_on:
      - db

volumes:
  pg_data:
